import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../../src/styles/global.scss";


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"]

});

export const metadata: Metadata = {
  title: "planets point",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>{children} </div>
      </body>
    </html>
  );
}
