import type { Metadata } from "next";

import "../../src/styles/global.scss";



export const metadata: Metadata = {
  title: "planets point",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
